import Head from "next/head";
import logo from "../public/contact.svg";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import styled from "styled-components";
import logo2 from "../public/logo.svg";

export default function Home() {
  return (
    <HomeContainer>
      <Head>
        <title>OuterBase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ContactWrapper>
        <ContactContainer>
          <Text>
            Contact Outerbase today for all your ICT, Real Estate <br />
            and General Contract needs
          </Text>
          <ContactButton>Get In Touch</ContactButton>
        </ContactContainer>
      </ContactWrapper>
      <Square></Square>
      <Square2></Square2>
      <FooterWrapper>
        <FooterContainer>
          <Image src={logo2} width={226} height={48} alt="outerbase-img" />
          <FooterText>© 2022, Outerbase, All rights reserved.</FooterText>
        </FooterContainer>
      </FooterWrapper>
    </HomeContainer>
  );
}

const HomeContainer = styled.div`
  display: relative;
`;

const Square = styled.div`
  width: 110px;
  height: 192px;
  background: url("../square.png") no-repeat;
  position: absolute;
  // background-color: red;
  left: 0.99rem;
  top: 5.9rem;
  z-index: 100;
`;
const Square2 = styled.div`
  width: 110px;
  height: 192px;
  background: url("../square.png") no-repeat;
  position: absolute;
  // background-color: red;
  right: 0.1rem;
  bottom: 20.5rem;
  z-index: 100;
`;
const FooterWrapper = styled.footer`
  width: 100%;
  height: 209px;
  background: #ededed;
  display: flex;
  justify-content: center;
  align-items: center;
`;
const FooterContainer = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const FooterText = styled.p`
  font-size: 18px;
  line-height: 28px;
  text-align: center;
  letter-spacing: -0.246165px;
  color: #000000;

  mix-blend-mode: normal;
  opacity: 0.5;
`;
const MainComponent = styled.main`
  width: 100%;
  height: 80vh;
  display: grid;
  padding: 0 224px;
  grid-template-columns: repeat(4, 1fr);
  grid-template-rows: repeat(4, 1fr);
  background-color: #fff;
`;
const DashOne = styled.div`
  display: absolute;
  top: 4rem;
`;
const ParaOne = styled.p`
  width: 772px;
  height: 352px;
  font-style: normal;
  font-weight: normal;
  font-size: 24px;
  line-height: 58px;
  color: #000000;
  grid-column: 1 / 3;
  grid-row: 1 / 2;
`;
const ParaTwo = styled.p`
  width: 772px;
  height: 175px;
  font-style: normal;
  font-weight: normal;
  font-size: 20px;
  line-height: 88px;
  text-align: right;
  color: #000000;
  grid-column: 3 / 4;
  grid-row: 2 / 3;
`;

const ContactWrapper = styled.div`
  width: 100%;
  height: 300px;
  background: #101417;
  display: flex;
  justify-content: center;
  align-items: center;
`;
const ContactContainer = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  display: relative;
`;

const ImageCont = styled.div`
  display: absolute;
  right: 80rem;
`;

const Text = styled.p`
  width: 1163px;
  font-weight: normal;
  font-size: 28px;
  line-height: 64px;
  color: #ffffff;
  text-align: center;
`;
const ContactButton = styled.button`
  width: 200px;
  height: 50px;
  background: rgba(255, 255, 255, 0.12);
  border: 2px solid #ffffff;
  box-shadow: 0px 8px 4px rgba(0, 0, 0, 0.25);
  border-radius: 16px;
  font-weight: 600;
  font-size: 14px;
  line-height: 0px;
  color: #ffffff;
`;

const FooterComponent = styled.div`
  width: 1728px;
  height: 209px;
`;
const CopyRight = styled.p`
  font-size: 14px;
  font-style: normal;
  font-weight: 400;
  line-height: 28px;
  letter-spacing: -0.25px;
  text-align: center;
`;
