import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import styled from "styled-components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>OuterBase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Outerbases</p>
      <Link href="/contact">
        <a>Contact</a>
      </Link>
    </div>
  );
}
