import Head from "next/head";
import logo from "../public/contact.svg";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import styled from "styled-components";

export default function Home() {
  return (
    <>
      <Head>
        <title>OuterBase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactContainer>
        {/* <ImageCont>
          <Image src={logo} width={82} height={82} alt="img" />
        </ImageCont> */}
        <Text>
          Contact Outerbase today for all your ICT, Real Estate <br />
          and General Contract needs
        </Text>
        <ContactButton>Get In Touch</ContactButton>
      </ContactContainer>
    </>
  );
}

const ContactContainer = styled.div`
  width: 1728px;
  height: 300px;
  background: #101417;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  display: relative;
`;

const ImageCont = styled.div`
  display: absolute;
  right: 80rem;
`;

const Text = styled.p`
  width: 1163px;
  font-weight: normal;
  font-size: 28px;
  line-height: 64px;
  color: #ffffff;
  text-align: center;
`;
const ContactButton = styled.button`
  width: 200px;
  height: 50px;
  background: rgba(255, 255, 255, 0.12);
  border: 2px solid #ffffff;
  box-shadow: 0px 8px 4px rgba(0, 0, 0, 0.25);
  border-radius: 16px;
  font-weight: 600;
  font-size: 14px;
  line-height: 0px;
  color: #ffffff;
`;
